"""empty message

Revision ID: b6ecaf36fd4f
Revises: f3b91456d20e
Create Date: 2023-10-05 08:43:46.453846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ecaf36fd4f'
down_revision = 'f3b91456d20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('appointmentDate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('services', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('appointmentTime', sa.DateTime(), nullable=False))
        batch_op.drop_column('phone_number')
        batch_op.drop_column('appointment_date')
        batch_op.drop_column('appointment_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_datetime', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('appointment_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('appointmentTime')
        batch_op.drop_column('services')
        batch_op.drop_column('appointmentDate')
        batch_op.drop_column('phoneNumber')

    # ### end Alembic commands ###
