"""empty message

Revision ID: c5e2fd0ac194
Revises: b6ecaf36fd4f
Create Date: 2023-10-05 12:04:31.361215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e2fd0ac194'
down_revision = 'b6ecaf36fd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basic_facial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('back_facial', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('couples_facial', sa.Boolean(), nullable=True))
        batch_op.drop_column('basic_facial_quantity')
        batch_op.drop_column('services')
        batch_op.drop_column('back_facial_quantity')
        batch_op.drop_column('couples_facial_quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('couples_facial_quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('back_facial_quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('services', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('basic_facial_quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('couples_facial')
        batch_op.drop_column('back_facial')
        batch_op.drop_column('basic_facial')

    # ### end Alembic commands ###
