"""empty message

Revision ID: f3b91456d20e
Revises: 4622f2de4c46
Create Date: 2023-10-05 08:37:26.453796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b91456d20e'
down_revision = '4622f2de4c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullName', sa.String(length=100), nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('fullName')

    # ### end Alembic commands ###
